### ISSUE TITLE
Loading as file://path/messages.properties in Google Chrome

### ISSUE THREAD

**Issue by apetrichkovich** [suhaibkhan/messageResource.js#10]
I'm working on html5 app that works as file:///path/index.html.
When I try to load file://path/messages.properties in Google Chrome I get next error:
XMLHttpRequest cannot load file:///path/messages.properties. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

**Comment by suhaibkhan** [comment]
The best way to solve your problem is to run your app in a local server. Refer the following link to get more details - http://stackoverflow.com/questions/20041656/xmlhttprequest-cannot-load-file-cross-origin-requests-are-only-supported-for-ht
